# Generated by Django 4.2.26 on 2025-11-16 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='empresas_vinculadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
